### PR TITLE
add support for evil-shift-left and evil-shift-right

### LINKED ISSUE #5: support for evil-shift-left and evil-shift-right would be nice
see title.

### PR DESCRIPTION
**Pull request by wbolster**
closes #5.

### CODE REVIEW

**Comment by wbolster** [comment]
btw, is there a reason you repeat the whole argument list instead of using `&rest`?

**Comment by edkolev** [comment]
Thanks for this! I'll try to get this merged soon.

> btw, is there a reason you repeat the whole argument list instead of using &rest?

Yes, emacs has `funcall-interactively` but doesn't have `apply-interactively`.

If you want, you can try to re-implement this (or any other advice function) with `&rest`:
```
(defun evil-goggles--evil-delete-advice (orig-fun beg end &optional type register yank-handler)
  (evil-goggles--with-goggles beg end 'evil-goggles-delete-face
    (if
        (called-interactively-p 'any)
        (funcall-interactively orig-fun beg end type register yank-handler)
      (funcall orig-fun beg end type register yank-handler))))
```

**Comment by wbolster** [comment]
```elisp
(apply #'funcall-interactively args)
```

perhaps?

**Comment by edkolev** [comment]
This is now in master.

**Pull request closed without merging**
